name: viewtouch_ui
description: ViewTouch v2 POS Flutter frontend
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^5.1.0
  protobuf: ^6.0.0
  fixnum: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

dependency_overrides:
  googleapis_auth: ^2.3.0
  meta: ^1.18.2
  vector_math: ^2.3.0
  test_api: ^0.7.11
